version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: vehicle_tracker_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: vehicle_tracker
    volumes:
      - mongodb_data:/data/db
    networks:
      - vehicle_tracker_network

  redis:
    image: redis:7-alpine
    container_name: vehicle_tracker_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - vehicle_tracker_network

  backend:
    build: .
    container_name: vehicle_tracker_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://admin:password@mongodb:27017/vehicle_tracker?authSource=admin
      - REDIS_URL=redis://redis:6379
      - ENVIRONMENT=production
    depends_on:
      - mongodb
      - redis
    networks:
      - vehicle_tracker_network
    volumes:
      - ./logs:/app/logs

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: vehicle_tracker_frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - vehicle_tracker_network

volumes:
  mongodb_data:

networks:
  vehicle_tracker_network:
    driver: bridge